baseURL: https://ronalleva.com
disablePathToLower: true
languageCode: en-us
title: ronalleva.com
theme: hugo-coder

params:
  author: Ron Alleva
  info: A Developer
  social:
  - name: github
    weight: 1
    url: https://github.com/ronnie76er
  - name: keybase
    weight: 1
    url: https://keybase.io/ronnie76er
  - name: linkedin
    weight: 1
    url: https://www.linkedin.com/in/ronalleva/

menu:
  main:
  - name: "Blog"
    weight: 1
    url: /posts/
